version: '3.8'

services:
  api:
    container_name: my-dotnet-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - redis
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TaskDB;User Id=sa;Password=YourStrong!Passw0rd;
      - Redis__Connection=redis:6379

  db:
    container_name: sql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "vivek@1998"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  redis:
    container_name: redis-cache
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

volumes:
  sql_data:
